### ISSUE TITLE
Depending on Biobase

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/unimod#4]
The current version of `unimod` imports 3 symbols from `Biobase`:
-  `Versioned`
- `classVersion`
- `description`

I think that the trend in Bioc core is to drop the class version slot. Although it can be handy to update object from one class to another (rather than inspecting the slots one by one to figure out the old class definition), it can also be a substantial overhead when many object are created. I am wondering if it is really necessary to have a class version and if yes, then I think it is probably easier to have a plain `character` and from importing the two first symbols above. 

I am unsure if we thus still need to depend on `Biobase` for the `description` generic. The slot and/or accessor could simply be renamed `unimodName`. 

@sgibb, what do you think?

**Comment by sgibb** [comment]
I am not sure that we need a `version` slot. I thought it is code standard of Bioc S4 classes. But I am happy to drop that slot (and the dependency on `Biobase`).
