### ISSUE TITLE
Functions rather than generics/methods 

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/unimod#5]
I would suggest to simplify the code as much as possible and only use generics and methods when necessary. Currently, in `AllGenerics.R`, I think most generics have pretty specialised names anyway and, unless they are supposed to operate on multiple classes (currently only one is defined in the package, but more might be added), I would suggest to fall back to plain functions.

**Comment by sgibb** [comment]
Thanks for all your comments! I am not sure whether we need more classes. I will replace the methods by simple functions.
